language: generic
script: tar -zcvf eclipse-inst-linux64.tar.gz eclipse-inst-linux64
deploy:
  provider: releases
  api_key:
    secure: e5tZyT/EtBs2whaPcNU6D6dKTc5ZDhnZmae3iPepL58GEn/3zVpy53Kv1lNnPeG6EZHRkKKNK2yIZlDvNn12RBbYSnhuRxN2lL/iR4LZ+TIGHciO1SQBvByxFPhNcgXUuLaJQYSmkOJxCn6X0J6DgX7dqNcHczUUdJkkUO/0wo1+/gPKUIl8tcwMgFpr13PjQRQkaLiXzdThE+5tQKGEf1/BceJXmCYnJzoDF4iaeLzXXEobzhezTXyVMSbCfH7QbhXLvrfmY4rtzS2QEy+eE3ruWHzm0+NQCuY6xQdV7P+7BQlZ7QMhM4BuDuSZlT7mYEUuN5N9iTLHCp5L22n4bxIKkpxvqFi2T+6zN6GwkpK6Sz7UelAMYFHZUcd5BwUatB6s89d9P5+315ILgs3X9kkQyPjms6KUzYsN7nkJnz2nqtY8XSgCIE7C5HWDKgKWZXhp9zyEOQWlZ4AxXAUFLZ+gYnD3H5VD8Gcaxrn5D19gT2diBn8tRSFavA452fQNJoqOHg88sCFCFUQbSqcqjVOm+kxlMfvG3S98Exvrz8K9rubl9VeLtdyb1uPf2L3YTCgPIo4RwOGWLCVyo/16pmjBUk6LjDDPFT0PYapIumDP08/hDVZTHhx5W/1bC6fdawlOOA7CMUMoMtE/lWOKqEarBj+5nngX/pkqjrcKf+w=
  file: eclipse-inst-linux64.tar.gz
  skip_cleanup: true
  on:
    repo: MartinLoeper/KAMP-Linux-Installer
